export const JABATAN = {
  KETUA: "KETUA",
  ANGGOTA: "ANGGOTA",
  SEKRETARIS: "SEKRETARIS",

  KASUBBAG_HUKUM_DAN_SDM: "KASUBBAG_HUKUM_DAN_SDM",

  KASUBBAG_PERENCANAAN_DATA_DAN_INFORMASI:
    "KASUBBAG_PERENCANAAN_DATA_DAN_INFORMASI",

  KASUBBAG_KEUANGAN_UMUM_DAN_LOGISTIK: "KASUBBAG_KEUANGAN_UMUM_DAN_LOGISTIK",

  PENELAAH_TEKNIS_KEBIJAKAN: "PENELAAH_TEKNIS_KEBIJAKAN",

  PENATA_KELOLA_SISTEM_DAN_TEKNOLOGI_INFORMASI:
    "PENATA_KELOLA_SISTEM_DAN_TEKNOLOGI_INFORMASI",

  PENYUSUN_MATERI_HUKUM_DAN_PERUNDANG_UNDANGAN:
    "PENYUSUN_MATERI_HUKUM_DAN_PERUNDANG_UNDANGAN",

  PENATA_KELOLA_PEMILU: "PENATA_KELOLA_PEMILU",

  ARSIPARIS_TERAMPIL: "ARSIPARIS_TERAMPIL",

  OPERATOR_LAYANAN_OPERASIONAL: "OPERATOR_LAYANAN_OPERASIONAL",

  ADMINISTRASI_PERKANTORAN: "ADMINISTRASI_PERKANTORAN",
};

export const JABATAN_LABELS = {
  [JABATAN.KETUA]: "Ketua",
  [JABATAN.ANGGOTA]: "Anggota",
  [JABATAN.SEKRETARIS]: "Sekretaris",

  [JABATAN.KASUBBAG_HUKUM_DAN_SDM]: "Kasubbag Hukum dan SDM",

  [JABATAN.KASUBBAG_PERENCANAAN_DATA_DAN_INFORMASI]:
    "Kasubbag Perencanaan, Data dan Informasi",

  [JABATAN.KASUBBAG_KEUANGAN_UMUM_DAN_LOGISTIK]:
    "Kasubbag Keuangan, Umum dan Logistik",

  [JABATAN.PENELAAH_TEKNIS_KEBIJAKAN]: "Penelaah Teknis Kebijakan",

  [JABATAN.PENATA_KELOLA_SISTEM_DAN_TEKNOLOGI_INFORMASI]:
    "Penata Kelola Sistem dan Teknologi Informasi",

  [JABATAN.PENYUSUN_MATERI_HUKUM_DAN_PERUNDANG_UNDANGAN]:
    "Penyusun Materi Hukum dan Perundang-undangan",

  [JABATAN.PENATA_KELOLA_PEMILU]: "Penata Kelola Pemilu",

  [JABATAN.ARSIPARIS_TERAMPIL]: "Arsiparis Terampil",

  [JABATAN.OPERATOR_LAYANAN_OPERASIONAL]: "Operator Layanan Operasional",

  [JABATAN.ADMINISTRASI_PERKANTORAN]: "Administrasi Perkantoran",
};

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SEKRETARIS: "SEKRETARIS",
  KASUBBAG: "KASUBBAG",
  ADMIN_PPID: "ADMIN_PPID",
  USER: "USER",
};

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ADMIN,
  ROLES.SEKRETARIS,
  ROLES.KASUBBAG,
  ROLES.ADMIN_PPID,
];

export const URL_NOTIF = "http://localhost:8080/api/v1/notif";
